# Dependencies
markdown:         kramdown
rouge:            true

# Permalinks
permalink:        pretty

# Setup
title:            Wade R. Roberts
tagline:          'Evolutionary Genomics'
description:      'Postdoctoral Fellow'
institution:      'University of Arkansas'
url:              https://wrroberts.github.io
copyright-year:   2022

theme-cfg:
  avatar:         /images/wade.jpg
  background:     /images/pedunculata.jpg

author:
  name:           'Wade R. Roberts'
  twitter:        https://twitter.com/wwaaaddddeee
# facebook:       https://twitter.com/wwaaaddddeee
# instagram:      https://twitter.com/wwaaaddddeee
  github:         https://github.com/wrroberts
  scholar:        https://scholar.google.com/citations?user=FRciU2oAAAAJ
# dribbble:       https://twitter.com/wwaaaddddeee
  email:          wade.r.roberts@gmail.com
# email:          dr.roberts@achimen.es
#  mailing:        'French Ad 324<br /> PO Box 641030<br /> Pullman, WA  99164-1030<br /> United States'
#  phone:          '1-509-335-1716'

# paginate:         5

github:
  repo:           https://github.com/wrroberts/wrroberts.github.io
